---
- name: Desplegar / Actualizar SonarQube en MicroK8s
  hosts: controller
  connection: local
  vars_files:
    - ../vars/env.yml

  vars:
    release_name: sonarqube
    chart_repo: https://SonarSource.github.io/helm-chart-sonarqube
    chart_name: sonarqube/sonarqube
    k8s_tmp_dir: "/tmp/calendar-k8s"

  tasks:
    - name: Validar variables requeridas SonarQube
      ansible.builtin.assert:
        that:
          - SONARQUBE_NAMESPACE is defined
          - SONARQUBE_IMAGE is defined
          - SONARQUBE_HOST is defined
        fail_msg: "Faltan variables SONARQUBE_NAMESPACE, SONARQUBE_IMAGE o SONARQUBE_HOST en vars/env.yml"

    - name: Generar passcode de monitoring (si no está definido)
      ansible.builtin.set_fact:
        sonar_monitoring_passcode: "{{ SONARQUBE_MONITORING_PASSCODE | default(lookup('password', '/dev/null length=24 chars=ascii_letters,digits'), true) }}"

    - name: Crear namespace si no existe
      ansible.builtin.command: "microk8s kubectl create ns {{ SONARQUBE_NAMESPACE }}"
      register: create_ns
      failed_when: create_ns.rc not in [0,1]
      changed_when: create_ns.rc == 0

    - name: Habilitar addon ingress en MicroK8s (idempotente)
      ansible.builtin.command: microk8s enable ingress
      become: true
      register: ingress_enable
      changed_when: ingress_enable.stdout is not search('Nothing to do for ingress')

    - name: Habilitar addon helm3 en MicroK8s (idempotente)
      ansible.builtin.command: microk8s enable helm3
      become: true
      register: helm3_enable
      changed_when: helm3_enable.stdout is not search('Nothing to do for helm3')

    - name: Asegurar directorio temporal
      ansible.builtin.file:
        path: "{{ k8s_tmp_dir }}"
        state: directory
        mode: '0755'
      become: true

    - name: Añadir repo Helm SonarSource (no falla si ya existe)
      ansible.builtin.command: microk8s helm3 repo add sonarqube {{ chart_repo }}
      register: helm_repo
      failed_when: false
      changed_when: (helm_repo.stdout | default('')) is search('has been added')
    - name: Calcular imagen repo y tag de SonarQube
      ansible.builtin.set_fact:
        sq_image_repo: "{{ (SONARQUBE_IMAGE | string).split(':')[0] }}"
        sq_image_tag: "{{ (SONARQUBE_IMAGE | string).split(':')[1] if ':' in (SONARQUBE_IMAGE | string) else 'latest' }}"


    - name: Actualizar repos Helm
      ansible.builtin.command: microk8s helm3 repo update

    - name: Calcular flags de persistencia para SonarQube
      ansible.builtin.set_fact:
        persistence_flags: >-
          {{ '--set persistence.enabled=true --set persistence.size=' ~ SONARQUBE_STORAGE_SIZE
             if (SONARQUBE_STORAGE_SIZE is defined and (SONARQUBE_STORAGE_SIZE | length) > 0)
             else '--set persistence.enabled=false' }}

    - name: Habilitar storage en MicroK8s si se usa persistencia (idempotente)
      ansible.builtin.command: microk8s enable storage
      become: true
      when: persistence_flags is search('enabled=true')
      register: storage_enable
      changed_when: (storage_enable.stdout | default('')) is not search('Nothing to do for storage')

    - name: Configurar flags de edición Community
      ansible.builtin.set_fact:
        edition_flags: "--set community.enabled=true"

    - name: Desplegar / Actualizar SonarQube vía Helm (Community)
      ansible.builtin.command: >-
        microk8s helm3 upgrade --install {{ release_name }} {{ chart_name }}
        --namespace {{ SONARQUBE_NAMESPACE }}
        --set image.repository={{ sq_image_repo }}
        --set image.tag={{ sq_image_tag }}
        --set ingress.enabled=true
        --set ingress.ingressClassName=public
        --set ingress.hosts[0].name={{ SONARQUBE_HOST }}
        --set ingress.hosts[0].path=/
        --set monitoringPasscode={{ sonar_monitoring_passcode }}
        --set resources.requests.memory={{ SONARQUBE_MEMORY_REQUEST | default('1Gi') }}
        --set resources.requests.cpu={{ SONARQUBE_CPU_REQUEST | default('250m') }}
        --set resources.limits.memory={{ SONARQUBE_MEMORY_LIMIT | default('2Gi') }}
        --set resources.limits.cpu={{ SONARQUBE_CPU_LIMIT | default('1') }}
        {{ edition_flags }}
        {{ persistence_flags }}
      register: helm_deploy
      changed_when: helm_deploy.rc == 0

    - name: Esperar a que los pods estén ready
      ansible.builtin.shell: >-
        microk8s kubectl -n {{ SONARQUBE_NAMESPACE }} get pods -l app.kubernetes.io/name=sonarqube -o jsonpath='{.items[*].status.containerStatuses[*].ready}'
      register: pod_ready
      retries: 40
      delay: 15
      until: pod_ready.stdout is search('true')
      changed_when: false

    - name: Mostrar services SonarQube
      ansible.builtin.command: "microk8s kubectl -n {{ SONARQUBE_NAMESPACE }} get svc"
      register: svc_out
      changed_when: false

    - name: Mostrar ingress SonarQube
      ansible.builtin.command: "microk8s kubectl -n {{ SONARQUBE_NAMESPACE }} get ingress"
      register: ing_out
      changed_when: false

    - name: Instrucciones acceso SonarQube
      ansible.builtin.debug:
        msg:
          - "Añade en tu PC: <IP_CLUSTER>  {{ SONARQUBE_HOST }}"
          - "Usuario/Password inicial: admin / admin (se pedirá cambio la primera vez)"
          - "Genera un token personal en SonarQube (My Account > Security) para Azure DevOps"
