---
- name: Desplegar SonarQube en Worker vía Docker
  hosts: workers
  become: true
  vars_files:
    - ../vars/env.yml

  vars:
    container_name: sonarqube

  tasks:
    - name: Validar variables requeridas
      ansible.builtin.assert:
        that:
          - SONARQUBE_DOCKER_IMAGE is defined
          - SONARQUBE_PORT is defined
          - SONARQUBE_DATA_DIR is defined
          - SONARQUBE_RUN_USER is defined
        fail_msg: "Faltan variables SONARQUBE_DOCKER_IMAGE/PORT/DATA_DIR/RUN_USER en vars/env.yml"

    - name: Asegurar vm.max_map_count requerido por Elasticsearch
      block:
        - name: Configurar vm.max_map_count de forma persistente
          ansible.builtin.lineinfile:
            path: /etc/sysctl.conf
            regexp: '^vm.max_map_count='
            line: 'vm.max_map_count=262144'
            state: present
          notify: Reload sysctl

        - name: Aplicar vm.max_map_count inmediatamente
          ansible.builtin.command: sysctl -w vm.max_map_count=262144
          changed_when: false

    - name: Comprobar si docker ya está instalado
      ansible.builtin.command: which docker
      register: docker_which
      changed_when: false
      failed_when: false

    - name: Instalar prerequisitos de Docker (apt repos) si no existe docker
      ansible.builtin.package:
        name:
          - apt-transport-https
          - ca-certificates
          - curl
          - gnupg
          - lsb-release
        state: present
      when: docker_which.rc != 0

    - name: Instalar Docker (paquete distro) si no existe
      ansible.builtin.package:
        name: docker.io
        state: present
      when: docker_which.rc != 0

    - name: Asegurar servicio Docker iniciado
      ansible.builtin.systemd:
        name: docker
        state: started
        enabled: true

    - name: Localizar binario de docker
      block:
        - name: Revisar /usr/bin/docker
          ansible.builtin.stat:
            path: /usr/bin/docker
          register: docker_usrbin

        - name: Revisar /snap/bin/docker
          ansible.builtin.stat:
            path: /snap/bin/docker
          register: docker_snapbin

        - name: Definir variable docker_bin
          ansible.builtin.set_fact:
            docker_bin: >-
              {{ '/usr/bin/docker' if docker_usrbin.stat.exists else (
                 '/snap/bin/docker' if docker_snapbin.stat.exists else 'docker') }}

    - name: Asegurar grupo docker
      ansible.builtin.group:
        name: docker
        state: present

    - name: Añadir usuario al grupo docker
      ansible.builtin.user:
        name: "{{ SONARQUBE_RUN_USER }}"
        groups: docker
        append: true
      when: SONARQUBE_RUN_USER != 'root'

    - name: Crear directorio de datos
      ansible.builtin.file:
        path: "{{ SONARQUBE_DATA_DIR }}"
        state: directory
        owner: "{{ SONARQUBE_RUN_USER }}"
        group: "{{ SONARQUBE_RUN_USER }}"
        mode: '0755'

    - name: Crear directorio para logs
      ansible.builtin.file:
        path: "{{ SONARQUBE_DATA_DIR }}/logs"
        state: directory
        owner: "{{ SONARQUBE_RUN_USER }}"
        group: "{{ SONARQUBE_RUN_USER }}"
        mode: '0755'

    - name: Crear archivo systemd de SonarQube (docker run)
      ansible.builtin.copy:
        dest: /etc/systemd/system/sonarqube.service
        mode: '0644'
        content: |
          [Unit]
          Description=SonarQube (Docker)
          After=network-online.target docker.service
          Wants=network-online.target
          Requires=docker.service

          [Service]
          Type=simple
          User={{ SONARQUBE_RUN_USER }}
          Group={{ SONARQUBE_RUN_USER }}
          LimitNOFILE=65536
          Restart=always
          RestartSec=10
          # No usar --rm para poder inspeccionar el contenedor si falla
          ExecStartPre=/bin/sh -c '{{ docker_bin }} rm -f {{ container_name }} || true'
          ExecStart={{ docker_bin }} run \
            --name {{ container_name }} \
            -p {{ SONARQUBE_PORT }}:9000 \
            -v {{ SONARQUBE_DATA_DIR }}:/opt/sonarqube/data \
            -v {{ SONARQUBE_DATA_DIR }}/logs:/opt/sonarqube/logs \
            --ulimit nofile=65536:65536 \
            -e SONAR_ES_BOOTSTRAP_CHECKS_DISABLE=true \
            {{ SONARQUBE_DOCKER_IMAGE }}
          ExecStop={{ docker_bin }} stop {{ container_name }}

          [Install]
          WantedBy=multi-user.target

    - name: Recargar systemd
      ansible.builtin.command: systemctl daemon-reload

    - name: Iniciar servicio SonarQube
      ansible.builtin.systemd:
        name: sonarqube.service
        state: started
        enabled: true

    - name: Esperar a que SonarQube responda (hasta 5 min)
      ansible.builtin.uri:
        url: "http://{{ ansible_host }}:{{ SONARQUBE_PORT }}"
        return_content: false
        status_code: 200
      register: sq_http
      retries: 30
      delay: 10
      until: sq_http.status == 200
      ignore_errors: true

    - name: Obtener logs del contenedor si no respondió
      ansible.builtin.command: "{{ docker_bin }} logs --tail=120 {{ container_name }}"
      register: sq_logs
      changed_when: false
      when: sq_http.status is not defined or sq_http.status != 200
      ignore_errors: true

    - name: Mostrar estado inicial del contenedor
      ansible.builtin.command:
        argv:
          - "{{ docker_bin }}"
          - ps
          - "--filter"
          - "name=sonarqube"
          - "--format"
          - "{{ '{{.Names}}\\t{{.Status}}' }}"
      register: docker_status
      changed_when: false

    - name: Mostrar estado del servicio systemd (si hubo fallo)
      ansible.builtin.command: systemctl status sonarqube --no-pager
      register: sonarqube_unit_status
      changed_when: false
      when: sq_http.status is not defined or sq_http.status != 200
      ignore_errors: true

    - name: Mostrar journal de sonarqube (últimas 100 líneas, si hubo fallo)
      ansible.builtin.command: journalctl -u sonarqube --no-pager -n 100
      register: sonarqube_journal
      changed_when: false
      when: sq_http.status is not defined or sq_http.status != 200
      ignore_errors: true

    - name: Mostrar últimos logs SonarQube (si hubo fallo)
      ansible.builtin.debug:
        var: sq_logs.stdout_lines
      when: sq_logs is defined

    - name: Imprimir instrucciones de acceso
      ansible.builtin.debug:
        msg:
          - "Añade en tu PC /etc/hosts: <IP_WORKER>  {{ SONARQUBE_HOST | default('sonar.local') }}"
          - "Accede a: http://{{ SONARQUBE_HOST | default(ansible_host) }}:{{ SONARQUBE_PORT }}"
          - "Usuario/Password inicial: admin / admin"
          - "Genera token: Administrador (avatar) -> My Account -> Security -> Generate Token"
          - "Usa ese token en Azure DevOps Service Connection 'SonarQube-Service'"

  handlers:
    - name: Reload sysctl
      ansible.builtin.command: sysctl -p
      changed_when: false

  # (Las tareas de despliegue del play anterior van arriba; limpieza se mueve a un segundo play.)

- name: Limpieza opcional de SonarQube Docker
  hosts: workers
  become: true
  vars_files:
    - ../vars/env.yml
  tasks:
    - name: Parar servicio
      ansible.builtin.systemd:
        name: sonarqube.service
        state: stopped
      tags: [cleanup]

    - name: Eliminar servicio systemd
      ansible.builtin.file:
        path: /etc/systemd/system/sonarqube.service
        state: absent
      tags: [cleanup]

    - name: Eliminar datos (opcional y destructivo)
      ansible.builtin.file:
        path: "{{ SONARQUBE_DATA_DIR }}"
        state: absent
      tags: [cleanup]

    - name: Eliminar imagen (opcional)
      ansible.builtin.command: docker rmi {{ SONARQUBE_DOCKER_IMAGE }}
      ignore_errors: true
      tags: [cleanup]
