---
- name: Actualizar solo el Frontend (Calendar) en MicroK8s
  hosts: controller
  connection: local
  vars_files:
    - ../vars/env.yml

  vars:
    k8s_tmp_dir: "/tmp/calendar-k8s"

  tasks:
    - name: Validar que K8S_NAMESPACE esté definido (proveer en vars/env.yml o via -e)
      ansible.builtin.assert:
        that:
          - K8S_NAMESPACE is defined
          - K8S_NAMESPACE | length > 0
        fail_msg: "K8S_NAMESPACE no está definido. Establécelo en Ansible/vars/env.yml o pásalo con -e K8S_NAMESPACE=<namespace>."

    - name: Validar que FRONTEND_IMAGE esté definido
      ansible.builtin.assert:
        that:
          - FRONTEND_IMAGE is defined
          - FRONTEND_IMAGE | length > 0
        fail_msg: "FRONTEND_IMAGE no está definido. Establécelo en Ansible/vars/env.yml."

    - name: Verificar que el Namespace existe (prerrequisito)
      ansible.builtin.command: "microk8s kubectl get ns {{ K8S_NAMESPACE }}"
      changed_when: false
      register: ns_check
      failed_when: ns_check.rc != 0

    - name: Crear directorio temporal para manifests (si no existe)
      ansible.builtin.file:
        path: "{{ k8s_tmp_dir }}"
        state: directory
        mode: '0755'
        owner: "{{ ansible_user_id }}"
        group: "{{ ansible_user_id }}"
        recurse: true
      become: true

    - name: Render Frontend configmap (nginx)
      ansible.builtin.template:
        src: ../templates/k8s/frontend-configmap.yaml.j2
        dest: "{{ k8s_tmp_dir }}/30-frontend-configmap.yaml"

    - name: Render Frontend deployment
      ansible.builtin.template:
        src: ../templates/k8s/frontend-deployment.yaml.j2
        dest: "{{ k8s_tmp_dir }}/31-frontend-deployment.yaml"

    - name: Render Frontend service
      ansible.builtin.template:
        src: ../templates/k8s/frontend-service.yaml.j2
        dest: "{{ k8s_tmp_dir }}/32-frontend-service.yaml"

    - name: Aplicar Frontend (configmap, deployment y service)
      ansible.builtin.shell: |
        set -e
        microk8s kubectl -n {{ K8S_NAMESPACE }} apply -f {{ k8s_tmp_dir }}/30-frontend-configmap.yaml
        microk8s kubectl -n {{ K8S_NAMESPACE }} apply -f {{ k8s_tmp_dir }}/31-frontend-deployment.yaml
        microk8s kubectl -n {{ K8S_NAMESPACE }} apply -f {{ k8s_tmp_dir }}/32-frontend-service.yaml
      args:
        executable: /bin/bash

    - name: Reiniciar rollout del Frontend para tomar cambios de ConfigMap
      ansible.builtin.command: "microk8s kubectl -n {{ K8S_NAMESPACE }} rollout restart deployment/calendar-frontend"

    - name: Esperar a que Frontend esté listo
      ansible.builtin.command: "microk8s kubectl -n {{ K8S_NAMESPACE }} rollout status deployment/calendar-frontend --timeout=600s"
      register: rollout_fe
      retries: 10
      delay: 5
      until: rollout_fe.rc == 0

    - name: Mostrar Services en el namespace
      ansible.builtin.command: "microk8s kubectl -n {{ K8S_NAMESPACE }} get svc"
      register: svc_out
      changed_when: false

    - name: Imprimir Services
      ansible.builtin.debug:
        var: svc_out.stdout_lines
