---
- name: Remover SonarQube Docker del worker (contenedor y datos)
  hosts: workers
  become: true
  vars_files:
    - ../vars/env.yml

  vars:
    container_name: sonarqube

  tasks:
    - name: Validar variables
      ansible.builtin.assert:
        that:
          - SONARQUBE_DATA_DIR is defined
          - SONARQUBE_DOCKER_IMAGE is defined
        fail_msg: "Faltan SONARQUBE_DATA_DIR o SONARQUBE_DOCKER_IMAGE en vars/env.yml"

    - name: Parar servicio systemd de SonarQube si existe
      ansible.builtin.systemd:
        name: sonarqube.service
        state: stopped
      ignore_errors: true

    - name: Deshabilitar servicio systemd de SonarQube si existe
      ansible.builtin.systemd:
        name: sonarqube.service
        enabled: false
      ignore_errors: true

    - name: Eliminar archivo de servicio systemd
      ansible.builtin.file:
        path: /etc/systemd/system/sonarqube.service
        state: absent

    - name: Recargar systemd
      ansible.builtin.command: systemctl daemon-reload

    - name: Detectar binario docker (cleanup)
      ansible.builtin.shell: "PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/snap/bin command -v docker"
      register: docker_cmd_cleanup
      changed_when: false
      failed_when: false

    - name: Definir docker_bin cleanup
      ansible.builtin.set_fact:
        docker_bin: "{{ (docker_cmd_cleanup.stdout | trim) if (docker_cmd_cleanup.rc == 0 and (docker_cmd_cleanup.stdout | trim) != '') else 'docker' }}"

    - name: Parar contenedor si quedó corriendo
      ansible.builtin.command: "{{ docker_bin }} stop {{ container_name }}"
      ignore_errors: true

    - name: Eliminar contenedor si existe
      ansible.builtin.command: "{{ docker_bin }} rm -f {{ container_name }}"
      ignore_errors: true

    - name: Eliminar imagen (opcional)
      ansible.builtin.command: "{{ docker_bin }} rmi {{ SONARQUBE_DOCKER_IMAGE }}"
      ignore_errors: true

    - name: Eliminar datos en {{ SONARQUBE_DATA_DIR }} (¡destructivo!)
      ansible.builtin.file:
        path: "{{ SONARQUBE_DATA_DIR }}"
        state: absent

---
- name: Remover Ingress y recursos K8s (Service/Endpoints) usados para SonarQube Docker
  hosts: controller
  connection: local
  vars_files:
    - ../vars/env.yml

  tasks:
    - name: Eliminar Ingress
      ansible.builtin.command: "microk8s kubectl -n {{ K8S_NAMESPACE }} delete ingress sonarqube-docker-ingress --ignore-not-found"

    - name: Eliminar Service externo
      ansible.builtin.command: "microk8s kubectl -n {{ K8S_NAMESPACE }} delete service sonarqube-docker-ext --ignore-not-found"

    - name: Eliminar Endpoints del Service externo
      ansible.builtin.command: "microk8s kubectl -n {{ K8S_NAMESPACE }} delete endpoints sonarqube-docker-ext --ignore-not-found"
