---
- name: Limpiar servicios legacy (LoadBalancer y duplicados)
  hosts: controller
  vars_files:
    - vars/env.yml

  vars:
    K8S_NAMESPACE_DEFAULT: "calendar-app"

  tasks:
    - name: Establecer namespace por defecto si no está definido
      ansible.builtin.set_fact:
        K8S_NAMESPACE: "{{ K8S_NAMESPACE | default(K8S_NAMESPACE_DEFAULT) }}"

    - name: Mostrar namespace efectivo
      ansible.builtin.debug:
        msg: "Usando namespace: {{ K8S_NAMESPACE }}"

    - name: Eliminar Service legacy calendar-frontend-lb (LoadBalancer)
      ansible.builtin.command: "microk8s kubectl -n {{ K8S_NAMESPACE }} delete svc calendar-frontend-lb --ignore-not-found"
      become: false

    - name: Eliminar Service legacy calendar-backend-lb (LoadBalancer)
      ansible.builtin.command: "microk8s kubectl -n {{ K8S_NAMESPACE }} delete svc calendar-backend-lb --ignore-not-found"
      become: false

    - name: Eliminar Service duplicado mongodb (si existe)
      ansible.builtin.command: "microk8s kubectl -n {{ K8S_NAMESPACE }} delete svc mongodb --ignore-not-found"
      become: false

    - name: Listar Services tras limpieza
      ansible.builtin.command: "microk8s kubectl -n {{ K8S_NAMESPACE }} get svc"
      register: svc_out
      become: false

    - name: Imprimir Services actuales
      ansible.builtin.debug:
        var: svc_out.stdout_lines
