---
- name: Install Docker, clone repo and run docker compose
  hosts: localhost
  become: yes
  vars:
    project_repo: "https://github.com/JhoannPV/Ansible.git"
    project_path: "/home/sysadmin/ansible_project"
    project_branch: "main"

  tasks:
    - name: Ensure apt cache is updated
      ansible.builtin.apt:
        update_cache: yes
      when: ansible_os_family == "Debian"

    - name: Install Docker and Compose plugin if not present
      ansible.builtin.package:
        name:
          - docker.io
          - docker-compose-plugin
        state: present

    - name: Ensure project directory exists
      ansible.builtin.file:
        path: "{{ project_path }}"
        state: directory
        owner: sysadmin
        group: sysadmin
        mode: '0755'

    - name: Clone or update the repository
      ansible.builtin.git:
        repo: "{{ project_repo }}"
        dest: "{{ project_path }}"
        version: "{{ project_branch }}"
        update: yes
        force: yes
      become_user: sysadmin

    - name: Run docker compose up -d
      community.docker.docker_compose_v2:
        project_src: "{{ project_path }}"
        state: present
