---
# Uso:
# - Asegúrate de tener un inventory con los grupos `controller` y `workers`.
# - Ejecuta desde tu PC (control node) con:
#     ansible-playbook -i inventory.ini enable_master_ssh_to_workers.yml

- name: Generar clave SSH en Master y traer la clave pública
  hosts: controller
  gather_facts: false
  become: false
  vars:
    # Forzar configuración de conexión incluso si se ejecuta con sudo (root)
    ansible_connection: ssh
    ansible_user: sysadmin
    ansible_ssh_private_key_file: "/home/jhoann-bohorquez/.ssh/id_ed25519"
    ansible_become: false
    ansible_ssh_common_args: "-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null"

    # Usuario/paths en el host remoto (controller)
    ssh_user: "{{ ansible_user }}"
    ssh_home: "{{ '/root' if ssh_user == 'root' else '/home/' + ssh_user }}"
    master_keys_dir: "{{ playbook_dir }}/master_keys"
    master_pubkey_path: "{{ master_keys_dir }}/master_id_ed25519.pub"
  tasks:
    - name: Asegurar directorio local para guardar la clave pública (control node)
      ansible.builtin.file:
        path: "{{ master_keys_dir }}"
        state: directory
        mode: '0755'
      delegate_to: localhost
      run_once: true

    - name: Asegurar existencia de ~/.ssh en el master
      ansible.builtin.file:
        path: "{{ ssh_home }}/.ssh"
        state: directory
        mode: '0700'

    - name: Generar par de claves ed25519 en master si no existe
      ansible.builtin.command: "ssh-keygen -t ed25519 -f {{ ssh_home }}/.ssh/id_ed25519 -N '' -C 'ansible-generated-master-key'"
      args:
        creates: "{{ ssh_home }}/.ssh/id_ed25519.pub"

    - name: Asegurar permisos de la clave privada y pública
      ansible.builtin.file:
        path: "{{ item.path }}"
        mode: "{{ item.mode }}"
      loop:
        - { path: "{{ ssh_home }}/.ssh/id_ed25519", mode: '0600' }
        - { path: "{{ ssh_home }}/.ssh/id_ed25519.pub", mode: '0644' }

    - name: Traer la clave pública del master al controlador
      ansible.builtin.fetch:
        src: "{{ ssh_home }}/.ssh/id_ed25519.pub"
        dest: "{{ master_pubkey_path }}"
        flat: yes

- name: Instalar la clave pública del master en los workers
  hosts: workers
  gather_facts: false
  become: false
  vars:
    # Forzar configuración de conexión incluso si se ejecuta con sudo (root)
    ansible_connection: ssh
    ansible_user: sysadmin
    ansible_ssh_private_key_file: "/home/jhoann-bohorquez/.ssh/id_ed25519"
    ansible_become: false
    ansible_ssh_common_args: "-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null"

    # Usuario/paths en los hosts remotos (workers)
    ssh_user: "{{ ansible_user }}"
    ssh_home: "{{ '/root' if ssh_user == 'root' else '/home/' + ssh_user }}"
    master_pubkey_path: "{{ playbook_dir }}/master_keys/master_id_ed25519.pub"
  tasks:
    - name: Asegurar existencia de ~/.ssh en el worker
      ansible.builtin.file:
        path: "{{ ssh_home }}/.ssh"
        state: directory
        owner: sysadmin
        group: sysadmin
        mode: '0700'

    - name: Añadir la clave pública del master a authorized_keys del worker
      ansible.builtin.authorized_key:
        user: sysadmin
        state: present
        key: "{{ lookup('file', master_pubkey_path) }}"
        manage_dir: yes

    - name: Asegurar permisos y propiedad de authorized_keys
      ansible.builtin.file:
        path: "{{ ssh_home }}/.ssh/authorized_keys"
        owner: sysadmin
        group: sysadmin
        mode: '0600'

    - name: Restaurar contexto SELinux si aplica (no falla si no está presente)
      ansible.builtin.command: "restorecon -Rv {{ ssh_home }}/.ssh"
      args:
        warn: false
      failed_when: false
