---
- name: Obtener información para exponer SonarQube
  hosts: controller
  vars_files:
    - ./vars/env.yml

  vars:
    sonarqube_namespace: "sonarqube"
    sonarqube_hostname: "sonarqube.local"

  tasks:
    - name: Obtener IP del nodo controlplane
      ansible.builtin.shell: hostname -I | awk '{print $1}'
      register: node_ip
      changed_when: false

    - name: Agregar entrada en /etc/hosts del nodo remoto
      ansible.builtin.lineinfile:
        path: /etc/hosts
        line: "{{ node_ip.stdout }} {{ sonarqube_hostname }}"
        state: present
        regexp: ".*{{ sonarqube_hostname }}$"
        backup: yes
      become: true

    - name: Guardar IP para uso local
      ansible.builtin.set_fact:
        ip_para_local: "{{ node_ip.stdout }}"

    - name: Mostrar instrucciones para máquina local
      ansible.builtin.debug:
        msg:
          - "═══════════════════════════════════════════════════════════════"
          - "  Configuración completada en el nodo remoto"
          - "═══════════════════════════════════════════════════════════════"
          - ""
          - "Para acceder desde tu máquina local, ejecuta este comando:"
          - ""
          - "  echo '{{ node_ip.stdout }} {{ sonarqube_hostname }}' | sudo tee -a /etc/hosts"
          - ""
          - "O agrega manualmente esta línea a /etc/hosts:"
          - ""
          - "  {{ node_ip.stdout }} {{ sonarqube_hostname }}"
          - ""
          - "Luego accede a: http://{{ sonarqube_hostname }}"
          - ""
          - "Credenciales:"
          - "  Usuario: admin"
          - "  Contraseña: admin"
          - "═══════════════════════════════════════════════════════════════"

    - name: Mostrar resultado
      ansible.builtin.debug:
        msg:
          - "{{ hosts_updated.changed | ternary('✓ Entrada agregada/actualizada en /etc/hosts', '✓ La entrada ya existía en /etc/hosts') }}"
          - ""
          - "═══════════════════════════════════════════════════════════════"
          - "  SonarQube está disponible en: http://{{ sonarqube_hostname }}"
          - "═══════════════════════════════════════════════════════════════"
          - ""
          - "Credenciales por defecto:"
          - "  Usuario: admin"
          - "  Contraseña: admin"
          - ""
          - "IMPORTANTE: Cambia la contraseña en el primer acceso"
          - ""
          - "Para verificar el estado:"
          - "  microk8s kubectl -n {{ sonarqube_namespace }} get pods"
          - "  microk8s kubectl -n {{ sonarqube_namespace }} get ingress"

    - name: Verificar conectividad (opcional)
      ansible.builtin.uri:
        url: "http://{{ sonarqube_hostname }}"
        method: GET
        status_code: [200, 302]
        timeout: 5
      register: connectivity_check
      failed_when: false
      changed_when: false

    - name: Mostrar estado de conectividad
      ansible.builtin.debug:
        msg: "{{ connectivity_check.status == 200 or connectivity_check.status == 302 | ternary('✓ SonarQube responde correctamente', '✗ No se pudo conectar a SonarQube. Verifica que los pods estén Running.') }}"
