---
- name: Exponer SonarQube - Configurar nodo remoto
  hosts: controller
  vars_files:
    - ./vars/env.yml

  vars:
    sonarqube_namespace: "sonarqube"
    sonarqube_hostname: "sonarqube.local"

  tasks:
    - name: Obtener IP del nodo controlplane
      ansible.builtin.shell: hostname -I | awk '{print $1}'
      register: node_ip
      changed_when: false

    - name: Agregar entrada en /etc/hosts del controlplane
      ansible.builtin.lineinfile:
        path: /etc/hosts
        line: "{{ node_ip.stdout }} {{ sonarqube_hostname }}"
        state: present
        regexp: ".*{{ sonarqube_hostname }}$"
        backup: yes
      become: true

    - name: Guardar IP del controlplane
      ansible.builtin.set_fact:
        controlplane_ip: "{{ node_ip.stdout }}"

- name: Exponer SonarQube - Configurar máquina local
  hosts: localhost
  connection: local
  gather_facts: no

  vars:
    sonarqube_hostname: "sonarqube.local"

  tasks:
    - name: Obtener IP del controlplane
      ansible.builtin.set_fact:
        controlplane_ip: "{{ hostvars[groups['controller'][0]]['controlplane_ip'] }}"

    - name: Agregar entrada en /etc/hosts de la máquina local
      ansible.builtin.lineinfile:
        path: /etc/hosts
        line: "{{ controlplane_ip }} {{ sonarqube_hostname }}"
        state: present
        regexp: ".*{{ sonarqube_hostname }}$"
        backup: yes
      become: true

    - name: Verificar conectividad a SonarQube
      ansible.builtin.uri:
        url: "http://{{ sonarqube_hostname }}"
        method: GET
        status_code: [200, 302]
        timeout: 10
      register: connectivity
      failed_when: false
      changed_when: false

    - name: Mostrar resultado final
      ansible.builtin.debug:
        msg:
          - "═══════════════════════════════════════════════════════════════"
          - "  ✓ SonarQube configurado exitosamente"
          - "═══════════════════════════════════════════════════════════════"
          - ""
          - "Acceso configurado:"
          - "  URL: http://{{ sonarqube_hostname }}"
          - "  IP: {{ controlplane_ip }}"
          - ""
          - "Estado: {{ connectivity.status is defined and (connectivity.status == 200 or connectivity.status == 302) | ternary('✓ Accesible', '✗ No accesible aún (espera unos segundos)') }}"
          - ""
          - "Credenciales:"
          - "  Usuario: admin"
          - "  Contraseña: admin"
          - ""
          - "IMPORTANTE: Cambia la contraseña en el primer acceso"
          - "═══════════════════════════════════════════════════════════════"
