---
- name: Exponer SonarQube mediante hosts
  hosts: controller
  connection: local
  vars_files:
    - ./vars/env.yml

  vars:
    sonarqube_namespace: "sonarqube"
    sonarqube_hostname: "sonarqube.local"

  tasks:
    - name: Obtener la IP del nodo donde corre el Ingress Controller
      ansible.builtin.shell: |
        microk8s kubectl get nodes -o jsonpath='{.items[0].status.addresses[?(@.type=="InternalIP")].address}'
      register: node_ip
      changed_when: false

    - name: Mostrar IP del nodo
      ansible.builtin.debug:
        msg: "IP del nodo: {{ node_ip.stdout }}"

    - name: Verificar si la entrada ya existe en /etc/hosts
      ansible.builtin.lineinfile:
        path: /etc/hosts
        line: "{{ node_ip.stdout }} {{ sonarqube_hostname }}"
        state: present
        regexp: ".*{{ sonarqube_hostname }}$"
        backup: yes
      become: true
      register: hosts_updated

    - name: Mostrar resultado
      ansible.builtin.debug:
        msg:
          - "{{ hosts_updated.changed | ternary('✓ Entrada agregada/actualizada en /etc/hosts', '✓ La entrada ya existía en /etc/hosts') }}"
          - ""
          - "═══════════════════════════════════════════════════════════════"
          - "  SonarQube está disponible en: http://{{ sonarqube_hostname }}"
          - "═══════════════════════════════════════════════════════════════"
          - ""
          - "Credenciales por defecto:"
          - "  Usuario: admin"
          - "  Contraseña: admin"
          - ""
          - "IMPORTANTE: Cambia la contraseña en el primer acceso"
          - ""
          - "Para verificar el estado:"
          - "  microk8s kubectl -n {{ sonarqube_namespace }} get pods"
          - "  microk8s kubectl -n {{ sonarqube_namespace }} get ingress"

    - name: Verificar conectividad (opcional)
      ansible.builtin.uri:
        url: "http://{{ sonarqube_hostname }}"
        method: GET
        status_code: [200, 302]
        timeout: 5
      register: connectivity_check
      failed_when: false
      changed_when: false

    - name: Mostrar estado de conectividad
      ansible.builtin.debug:
        msg: "{{ connectivity_check.status == 200 or connectivity_check.status == 302 | ternary('✓ SonarQube responde correctamente', '✗ No se pudo conectar a SonarQube. Verifica que los pods estén Running.') }}"
