---
- name: Exponer SonarQube mediante Ingress
  hosts: controller
  vars_files:
    - ./vars/env.yml

  vars:
    sonarqube_namespace: "sonarqube"
    sonarqube_hostname: "sonarqube.local"

  tasks:
    - name: Obtener la IP del nodo controlplane
      ansible.builtin.shell: hostname -I | awk '{print $1}'
      register: node_ip
      changed_when: false

    - name: Mostrar IP del nodo
      ansible.builtin.debug:
        msg: "IP del nodo controlplane: {{ node_ip.stdout }}"

    - name: Verificar estado del Ingress Controller
      ansible.builtin.command: "microk8s kubectl -n ingress get pods -o wide"
      register: ingress_pods
      changed_when: false

    - name: Mostrar estado del Ingress Controller
      ansible.builtin.debug:
        var: ingress_pods.stdout_lines

    - name: Verificar Ingress de SonarQube
      ansible.builtin.command: "microk8s kubectl -n {{ sonarqube_namespace }} get ingress sonarqube-ingress -o wide"
      register: ingress_info
      changed_when: false

    - name: Mostrar Ingress de SonarQube
      ansible.builtin.debug:
        var: ingress_info.stdout_lines

    - name: Verificar Service de SonarQube
      ansible.builtin.command: "microk8s kubectl -n {{ sonarqube_namespace }} get svc sonarqube -o wide"
      register: svc_info
      changed_when: false

    - name: Mostrar Service de SonarQube
      ansible.builtin.debug:
        var: svc_info.stdout_lines

    - name: Verificar Endpoints de SonarQube
      ansible.builtin.command: "microk8s kubectl -n {{ sonarqube_namespace }} get endpoints sonarqube -o wide"
      register: ep_info
      changed_when: false
      failed_when: false

    - name: Mostrar Endpoints de SonarQube
      ansible.builtin.debug:
        var: ep_info.stdout_lines

    - name: Agregar entrada en /etc/hosts del nodo controlplane
      ansible.builtin.lineinfile:
        path: /etc/hosts
        line: "{{ node_ip.stdout }} {{ sonarqube_hostname }}"
        state: present
        regexp: ".*{{ sonarqube_hostname }}$"
        backup: yes
      become: true

    - name: Verificar entrada en /etc/hosts del controlplane
      ansible.builtin.shell: cat /etc/hosts | grep {{ sonarqube_hostname }}
      register: hosts_check
      changed_when: false

    - name: Mostrar entrada en /etc/hosts
      ansible.builtin.debug:
        var: hosts_check.stdout

    - name: Probar conectividad desde el controlplane
      ansible.builtin.uri:
        url: "http://{{ sonarqube_hostname }}"
        method: GET
        status_code: [200, 302]
        timeout: 10
      register: remote_connectivity
      failed_when: false
      changed_when: false

    - name: Mostrar resultado de conectividad remota
      ansible.builtin.debug:
        msg: "Conectividad desde controlplane: {{ remote_connectivity.status is defined | ternary('✓ OK (Status: ' + (remote_connectivity.status | string) + ')', '✗ FALLO') }}"

    - name: Instrucciones finales
      ansible.builtin.debug:
        msg:
          - "═══════════════════════════════════════════════════════════════"
          - "  Configuración del nodo completada"
          - "═══════════════════════════════════════════════════════════════"
          - ""
          - "Ahora en TU MÁQUINA LOCAL, ejecuta este comando:"
          - ""
          - "  echo '{{ node_ip.stdout }} {{ sonarqube_hostname }}' | sudo tee -a /etc/hosts"
          - ""
          - "Luego abre tu navegador y accede a:"
          - ""
          - "  http://{{ sonarqube_hostname }}"
          - ""
          - "Credenciales:"
          - "  Usuario: admin"
          - "  Contraseña: admin"
          - ""
          - "Si no funciona, verifica:"
          - "  1. Que el comando anterior se ejecutó en TU PC"
          - "  2. Que los pods estén Running: microk8s kubectl -n {{ sonarqube_namespace }} get pods"
          - "  3. Que el Ingress tenga ADDRESS configurada"
          - "═══════════════════════════════════════════════════════════════"
