---
- name: Instalar Java en el agente de Azure DevOps
  hosts: controller
  vars_files:
    - ./vars/env.yml

  tasks:
    - name: Actualizar cache de apt
      ansible.builtin.apt:
        update_cache: yes
        cache_valid_time: 3600
      become: true

    - name: Buscar versiones de Java disponibles
      ansible.builtin.shell: apt-cache search openjdk | grep -E "openjdk-[0-9]+-jdk" | sort
      register: java_packages
      changed_when: false

    - name: Mostrar paquetes Java disponibles
      ansible.builtin.debug:
        var: java_packages.stdout_lines

    - name: Instalar OpenJDK (versión disponible)
      ansible.builtin.apt:
        name:
          - default-jdk
        state: present
      become: true

    - name: Verificar instalación de Java
      ansible.builtin.command: java -version
      register: java_version
      changed_when: false

    - name: Mostrar versión de Java
      ansible.builtin.debug:
        var: java_version.stderr_lines

    - name: Obtener la ruta de JAVA_HOME
      ansible.builtin.shell: update-alternatives --query java | grep 'Value:' | awk '{print $2}' | sed 's|/bin/java||'
      register: java_home_path
      changed_when: false

    - name: Establecer JAVA_HOME
      ansible.builtin.lineinfile:
        path: /etc/environment
        line: 'JAVA_HOME="{{ java_home_path.stdout }}"'
        regexp: '^JAVA_HOME='
        state: present
      become: true

    - name: Mostrar JAVA_HOME
      ansible.builtin.debug:
        msg: "JAVA_HOME configurado en: {{ java_home_path.stdout }}"

    - name: Verificar que el servicio del agente está corriendo
      ansible.builtin.systemd:
        name: vsts.agent.*.service
        state: restarted
      become: true
      ignore_errors: yes

    - name: Verificar capabilities del agente
      ansible.builtin.debug:
        msg:
          - "═══════════════════════════════════════════════════════════════"
          - "  Java instalado correctamente"
          - "═══════════════════════════════════════════════════════════════"
          - ""
          - "Versión instalada: {{ java_version.stderr_lines[0] | default('Java') }}"
          - "JAVA_HOME: {{ java_home_path.stdout }}"
          - ""
          - "El agente de Azure DevOps necesita reiniciarse para detectar Java."
          - ""
          - "Opciones para reiniciar el agente:"
          - ""
          - "1. Si el agente corre como servicio:"
          - "   sudo systemctl restart vsts.agent.*.service"
          - ""
          - "2. Si el agente corre manualmente:"
          - "   Detén el agente (Ctrl+C) y ejecuta nuevamente:"
          - "   cd ~/myagent && ./run.sh"
          - ""
          - "3. O reinicia desde Azure DevOps:"
          - "   Project Settings → Agent pools → myagent → Agents → Restart"
          - ""
          - "Después del reinicio, ejecuta el pipeline nuevamente."
          - "═══════════════════════════════════════════════════════════════"
