- name: Preparar nodos para SonarQube (sysctl vm.max_map_count)
  hosts: controller,workers
  gather_facts: false
  become: true

  tasks:
    - name: Establecer vm.max_map_count=524288 (runtime)
      ansible.builtin.command: sysctl -w vm.max_map_count=524288
      changed_when: false
      failed_when: false
    - name: Persistir vm.max_map_count en /etc/sysctl.d/99-sonarqube.conf
      ansible.builtin.copy:
        dest: /etc/sysctl.d/99-sonarqube.conf
        content: |
          vm.max_map_count=524288
        owner: root
        group: root
        mode: '0644'
      failed_when: false
    - name: Aplicar configuración sysctl persistente
      ansible.builtin.command: sysctl --system
      changed_when: false
      failed_when: false

- name: Instalar SonarQube self-hosted en MicroK8s
  hosts: controller
  gather_facts: false

  vars_files:
    - vars/sonarqube.yml

  vars:
    k8s_tmp_dir: "/tmp/sonarqube-k8s"

  pre_tasks:
    - name: Validar variables requeridas
      ansible.builtin.assert:
        that:
          - SONAR_NAMESPACE is defined and SONAR_NAMESPACE | length > 0
          - SONAR_DB_USER is defined and SONAR_DB_USER | length > 0
          - SONAR_DB_PASSWORD is defined and SONAR_DB_PASSWORD | length > 0
          - SONAR_DB_NAME is defined and SONAR_DB_NAME | length > 0
        fail_msg: "Faltan variables en vars/sonarqube.yml (SONAR_NAMESPACE, SONAR_DB_USER, SONAR_DB_PASSWORD, SONAR_DB_NAME)"

    - name: Esperar a que MicroK8s esté listo
      ansible.builtin.command: microk8s status --wait-ready
      changed_when: false

    - name: Comprobar acceso al API de Kubernetes (warm-up)
      ansible.builtin.command: microk8s kubectl get ns
      register: warmup
      changed_when: false
      retries: 5
      delay: 3
      until: warmup.rc == 0

    - name: Verificar acceso a kubernetes desde el controlador
      ansible.builtin.command: microk8s kubectl version --client=true --output=yaml
      changed_when: false
      failed_when: false

  tasks:
    - name: Crear directorio temporal para manifests
      ansible.builtin.file:
        path: "{{ k8s_tmp_dir }}"
        state: directory
        mode: '0755'

    - name: Render Namespace
      ansible.builtin.template:
        src: templates/k8s/sonarqube-namespace.yaml.j2
        dest: "{{ k8s_tmp_dir }}/00-namespace.yaml"

    - name: Render Secret de Base de Datos
      ansible.builtin.template:
        src: templates/k8s/sonarqube-db-secret.yaml.j2
        dest: "{{ k8s_tmp_dir }}/01-db-secret.yaml"
      no_log: true

    - name: Render PostgreSQL (PVC + Deployment + Service)
      ansible.builtin.template:
        src: templates/k8s/sonarqube-postgres.yaml.j2
        dest: "{{ k8s_tmp_dir }}/10-postgres.yaml"

    - name: Render SonarQube (PVCs + Deployment + Service)
      ansible.builtin.template:
        src: templates/k8s/sonarqube.yaml.j2
        dest: "{{ k8s_tmp_dir }}/20-sonarqube.yaml"

    - name: Aplicar Namespace
      ansible.builtin.command: "microk8s kubectl apply -f {{ k8s_tmp_dir }}/00-namespace.yaml"

    - name: Aplicar Secret DB
      ansible.builtin.command: "microk8s kubectl apply -f {{ k8s_tmp_dir }}/01-db-secret.yaml"

    - name: Desplegar PostgreSQL (con reintentos)
      ansible.builtin.command: "microk8s kubectl apply -f {{ k8s_tmp_dir }}/10-postgres.yaml"
      register: apply_pg
      retries: 5
      delay: 5
      until: apply_pg.rc == 0

    - name: Esperar a que PostgreSQL esté listo
      ansible.builtin.command: "microk8s kubectl -n {{ SONAR_NAMESPACE }} rollout status deployment/sonar-postgres --timeout=600s"

    - name: Desplegar SonarQube (con reintentos)
      ansible.builtin.command: "microk8s kubectl apply -f {{ k8s_tmp_dir }}/20-sonarqube.yaml"
      register: apply_sonar
      retries: 5
      delay: 5
      until: apply_sonar.rc == 0

    - name: Forzar reinicio controlado de SonarQube (rollout restart)
      ansible.builtin.command: "microk8s kubectl -n {{ SONAR_NAMESPACE }} rollout restart deployment/sonarqube"
      changed_when: true
      failed_when: false

    - block:
        - name: Esperar a que SonarQube esté listo (timeout extendido)
          ansible.builtin.command: "microk8s kubectl -n {{ SONAR_NAMESPACE }} rollout status deployment/sonarqube --timeout=1500s"
      rescue:
        - name: DIAGNÓSTICO deployment sonarqube (describe)
          ansible.builtin.command: "microk8s kubectl -n {{ SONAR_NAMESPACE }} describe deployment/sonarqube"
          changed_when: false
        - name: DIAGNÓSTICO replicas y pods
          ansible.builtin.command: "microk8s kubectl -n {{ SONAR_NAMESPACE }} get rs,pods -l app=sonarqube -o wide"
          changed_when: false
        - name: DIAGNÓSTICO describe ReplicaSet SonarQube (si existe)
          ansible.builtin.shell: |
            set -e
            RS=$(microk8s kubectl -n {{ SONAR_NAMESPACE }} get rs -l app=sonarqube -o jsonpath='{.items[0].metadata.name}' 2>/dev/null || true)
            if [ -n "$RS" ]; then
              microk8s kubectl -n {{ SONAR_NAMESPACE }} describe rs "$RS" || true
            else
              echo "No hay ReplicaSet sonarqube aún"
            fi
          changed_when: false
        - name: DIAGNÓSTICO describe Pod SonarQube (si existe)
          ansible.builtin.shell: |
            set -e
            POD=$(microk8s kubectl -n {{ SONAR_NAMESPACE }} get pods -l app=sonarqube -o jsonpath='{.items[0].metadata.name}' 2>/dev/null || true)
            if [ -n "$POD" ]; then
              microk8s kubectl -n {{ SONAR_NAMESPACE }} describe pod "$POD" || true
            else
              echo "No hay Pod sonarqube aún"
            fi
          changed_when: false
        - name: DIAGNÓSTICO eventos recientes
          ansible.builtin.command: "microk8s kubectl -n {{ SONAR_NAMESPACE }} get events --sort-by=.lastTimestamp"
          changed_when: false
        - name: DIAGNÓSTICO eventos Scheduling / OOM
          ansible.builtin.shell: |
            microk8s kubectl -n {{ SONAR_NAMESPACE }} get events --sort-by=.lastTimestamp | egrep -i 'FailedScheduling|Insufficient|evict|Preempt|OOM|BackOff' || true
          changed_when: false
        - name: DIAGNÓSTICO PVC y PV relacionados
          ansible.builtin.shell: |
            echo 'PVC:'
            microk8s kubectl -n {{ SONAR_NAMESPACE }} get pvc || true
            echo 'PV (filtrado sonarqube):'
            microk8s kubectl get pv | egrep -i 'sonarqube|NAME' || true
          changed_when: false
        - name: DIAGNÓSTICO logs últimos 200 líneas
          ansible.builtin.command: "microk8s kubectl -n {{ SONAR_NAMESPACE }} logs deploy/sonarqube --tail=200"
          changed_when: false
        - name: DIAGNÓSTICO logs internos de SonarQube (sonar/web/ce/es)
          ansible.builtin.shell: |
            set -e
            POD=$(microk8s kubectl -n {{ SONAR_NAMESPACE }} get pods -l app=sonarqube -o jsonpath='{.items[0].metadata.name}' 2>/dev/null || true)
            if [ -n "$POD" ]; then
              for f in sonar.log web.log ce.log es.log; do
                echo "===== /opt/sonarqube/logs/$f =====";
                microk8s kubectl -n {{ SONAR_NAMESPACE }} exec "$POD" -- sh -c "[ -f /opt/sonarqube/logs/$f ] && tail -n 200 /opt/sonarqube/logs/$f || echo 'no existe'" || true;
                echo;
              done
            else
              echo "No hay Pod sonarqube para extraer logs internos"
            fi
          changed_when: false
        - name: DIAGNÓSTICO logs previos del contenedor (si hubo reinicios)
          ansible.builtin.shell: |
            set -e
            POD=$(microk8s kubectl -n {{ SONAR_NAMESPACE }} get pods -l app=sonarqube -o jsonpath='{.items[0].metadata.name}' 2>/dev/null || true)
            if [ -n "$POD" ]; then
              microk8s kubectl -n {{ SONAR_NAMESPACE }} logs "$POD" -c sonarqube --previous --tail=200 || true
            else
              echo "No hay Pod sonarqube para logs previos"
            fi
          changed_when: false
        - name: Forzar fallo tras diagnóstico
          ansible.builtin.fail:
            msg: "SonarQube no alcanzó readiness dentro del tiempo. Ver diagnóstico anterior para causas (memoria, permisos, DB, probes)."

    - name: Mostrar servicio de SonarQube (ClusterIP)
      ansible.builtin.command: "microk8s kubectl -n {{ SONAR_NAMESPACE }} get svc sonarqube -o wide"
