---
- name: Pre-pull de imágenes en MicroK8s (containerd) en todos los nodos
  hosts: all
  become: true
  vars_files:
    - vars/env.yml
  tasks:
    - name: Validar imágenes requeridas (FRONTEND_IMAGE, BACKEND_IMAGE, MONGODB_IMAGE)
      ansible.builtin.assert:
        that:
          - FRONTEND_IMAGE is defined
          - FRONTEND_IMAGE | length > 0
          - BACKEND_IMAGE is defined
          - BACKEND_IMAGE | length > 0
          - MONGODB_IMAGE is defined
          - MONGODB_IMAGE | length > 0
        fail_msg: "Faltan variables de imagen. Define FRONTEND_IMAGE, BACKEND_IMAGE y MONGODB_IMAGE en Ansible/vars/env.yml."

    - name: Asegurar que microk8s esté corriendo
      ansible.builtin.command: microk8s status --wait-ready

    - name: Descargar imágenes necesarias
      ansible.builtin.command: "microk8s ctr images pull {{ item }}"
      loop:
        - "{{ FRONTEND_IMAGE }}"
        - "{{ BACKEND_IMAGE }}"
        - "{{ MONGODB_IMAGE }}"
        - "docker.io/library/busybox:1.36.1"
