---
- name: Desinstalar Vault y External Secrets de MicroK8s
  hosts: controller
  become: true
  tasks:
    - name: Deshabilitar MetalLB (LoadBalancer) en MicroK8s si está habilitado
      ansible.builtin.command: microk8s disable metallb
      ignore_errors: true

    - name: Intentar desinstalar Vault via helm3 (si existe)
      ansible.builtin.command: microk8s helm3 uninstall vault -n vault
      ignore_errors: true

    - name: Eliminar namespace vault (si existe)
      ansible.builtin.command: microk8s kubectl delete ns vault --ignore-not-found

    - name: Intentar desinstalar External Secrets Operator
      ansible.builtin.command: microk8s helm3 uninstall external-secrets -n external-secrets
      ignore_errors: true

    - name: Eliminar namespace external-secrets (si existe)
      ansible.builtin.command: microk8s kubectl delete ns external-secrets --ignore-not-found

    - name: Eliminar CRDs de external-secrets (best effort)
      ansible.builtin.shell: |
        set -e
        microk8s kubectl get crds | awk '/external-secrets/{print $1}' | xargs -r microk8s kubectl delete crd
      args:
        executable: /bin/bash
      ignore_errors: true
