# Update apt cache (Debian) and install base packages
- name: Update apt cache (Debian systems)
  ansible.builtin.apt:
    update_cache: yes
  when: ansible_os_family == "Debian"

- name: Install base packages
  ansible.builtin.package:
    name:
      - curl
      - git
      - openssh-server
    state: present

- name: Enable SSH service
  ansible.builtin.systemd:
    name: ssh
    enabled: yes
    state: started
  when: ansible_service_mgr == 'systemd'
