- name: Update apt cache (Debian)
  ansible.builtin.apt:
    update_cache: yes
  when: ansible_os_family == "Debian"

- name: Install base packages
  ansible.builtin.package:
    name:
      - curl
      - git
      - openssh-server
    state: present

- name: Enable SSH service
  ansible.builtin.systemd:
    name: ssh
    enabled: yes
  when: ansible_service_mgr == 'systemd'

- name: Start SSH service
  ansible.builtin.systemd:
    name: ssh
    state: started
  when: ansible_service_mgr == 'systemd'
