# Ensure sysadmin user exists and is in docker group
- name: Ensure sysadmin user exists
  ansible.builtin.user:
    name: sysadmin
    state: present
    shell: /bin/bash
    create_home: yes

- name: Add sysadmin to docker group
  ansible.builtin.user:
    name: sysadmin
    groups: docker
    append: yes

- name: Refresh group membership for current session
  ansible.builtin.shell: newgrp docker
  become: yes
  become_user: sysadmin
  ignore_errors: yes
